const STRINGS = {

	//Sohil

    GOOGLE_PALCES_API_KEY: 'AIzaSyClq-KQUvy9b60TbprysJkMgfX-m0y0Ej8',
    PREVIOUS:"PREVIOUS",

    FIRST_NAME:'FIRST NAME',
    LAST_NAME:'LAST NAME',
    EMAIL:'EMAIL',
    PASSWORD:'PASSWORD',
    NEXT:'NEXT',
    HOME:'HOME',
    CONTACT_INFORMATION:'CONTACT INFORMATION',
    WHATS_YOUR_NAME:"WHAT'S YOUR NAME AND EMAIL ADDRESS ?",


    //Service preference screen

    SERVICE_PREFERENCE:"SERVICE PREFERENCE",
    WHAT_KIND_OF_SERVICE:"WHAT KIND OF SERVICE WOULD YOU LIKE FROM US ?",
    SELECT_SERVICE:'Select service for',
    CONVINENCE:'Convinence',
    STYLE:'Style',
    GIFT:'Gift',
    CAN_DO_THIS_LATER:'Previous',
    CAN_DO_THIS_LATER_NEW:'Can do this later',
    

    // Child Information

    CHILD_NAME:"CHILD NAME",
    ENTER_CHILD_NAME:"ENTER YOUR CHILD INFORMATION",
    ENTER_OTHER_CHILD_INFO:"ENTER YOUR OTHER CHILD INFO",


    CHILD_INFORMATION:"CHILD INFORMATION",
    CHILD_BRAND_TITLE_ONE:"HOW DO YOU LIKE THE CLOTHES TO FIT ?",
    CHILD_FIT_OPTION_ONE:"True to size",
    CHILD_FIT_OPTION_TWO:"Size up, I like to get more wear",
    CHILD_FIT_OPTION_THREE:'Size down, my "son/daughter" is petit',
    CHILD_BRAND_TITLE_TWO:'WHERE DO YOU CURRENTLY SHOP FOR YOUR CHILD CLOTHINGS',
    OTHERS:'OTHERS',
    HINT_TEXT:'SHOP NAME GOES HERE',

    //Size and proprtion

    SELECT_SIZE_TITLE:"SELECT SIZE CHILD IS CURRENTLY WEARING",
    SELECT_SIZE_TITLE_TWO:"HOW WOULD YOU CHARACTERIZE YOUR CHILD PROPORTIONS",
    OPTION_ONE:'Average',
    OPTION_TWO:'Petite',
    OPTION_THREE:'Pudgy',


    //Pregnanacy
WHEN_YOUR_DUE_DATE:'WHEN IS YOUR DUE DATE',
WHEN_YOU_EXPECT_FIRST_BOX:"WHEN YOU WANT TO RECEIVE YOUR FIRST BOX",

//style
STYLE_INFORMATION:'STYLE INFORMATION',
STYLE_INFO_TITLE:"LIKE EVERYTHING THAT'S TOTALLY YOUR VIBE...",

//Talk to Us

TALK_TO_US_HEADER_TITLE:'Talk to Us',
HINT_TEXT_TALK:'Feel free to leave comment',
TALK_TO_US_DESCRIPTION:'ARE THERE ANY HARD RULES OR IMPORTANT DETAILS REGARDING YOUR PREFERENCES OR YOUR DRESSING NEEDS THAT YOU WANT US TO KNOW ',

//Billing Information

REFERAL_CODE:"Referal Code(if any)",
ADDRESS:"ADDRESS",
CITY:"CITY",
STATE:"STATE",
ZIP_CODE:"ZIP CODE",
COUNTRY:"COUNTRY",
PHONE_NUMBER:"PHONE NUMBER",

//Billing Payment 
CARD_HOLDER_NAME:"CARD HOLDER NAME",
CARD_NUMBER:"16 DIGIT CARD NUMBER",
EXPIRY_DATE:"EXPIRY DATE",
CVV:"CVV CODE",
ADDRESS:"ADDRESS",
CITY:"CITY",
STATE:"STATE",
ZIPCODE:"ZIPCODE",





}
export default STRINGS;
