const ACTION_TYPES = {

	//user login action keys 
	USER_NAME_CHANGED: 'USER_NAME',
	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
	SIGNUP_USER_RES: 'SIGNUP_USER_RES',
	FETCHING_DATA: 'FETCHING_DATA',
    RESET_DATA: 'RESET_DATA',
    
    FIRST_NAME_CHANGED:'FIRST_NAME_CHANGED',
    LAST_NAME_CHANGED:'LAST_NAME_CHANGED',
    EMAIL_CHANGED:'EMAIL_CHANGED',
    PASSWORD_CHANGED:'PASSWORD_CHANGED',
    CLEAR_RESPONSE:'CLEAR_RESPONSE',
    FETCH_SIGNUP_RESPONSE_DATA:'FETCH_SIGNUP_RESPONSE_DATA',
    SERVICE_PREF_RES:'SERVICE_PREF_RES',

    //pregnancy selection

    PREGNANCY_SELECTION_RES:'PREGNANCY_SELECTION_RES',

    //Kids selection

    KIDS_SELECTION_RES:'KIDS_SELECTION_RES',
    BRAND_NAME_CHANGED:'BRAND_NAME_CHANGED',
    BRAND_LIST_RES:'BRAND_LIST_RES',
    WHAT_TO_BUY_RES:'WHAT_TO_BUY_RES',

    //size and proportin

    SIZE_AND_PROPORTION_RES:'SIZE_AND_PROPORTION_RES',
    SEND_DATA_RES:'SEND_DATA_RES',
    SEND_BRAND_DATA_RES:'SEND_BRAND_DATA_RES',
    
     //child Infromation
     FETCH_CHILD_INFO_RESPONSE_DATA:"FETCH CHILD INFO RESPONSE DATA",
     CHILD_NAME_CHANGED:"CHILD NAME CHANGED",
     CHILD_INFO_RESPONSE:"CHILD INFO RESPONSE",
 
 
     //pregnancy selection
     PREGNANCY_SELECTION_RES:'PREGNANCY_SELECTION_RES',
     PREGNANCY_DUEDATE_RESPONSE:"PREGNANCY_DUEDATE_RESPONSE",

     //style info
     STYLE_LIST_RES:'STYLE_LIST_RES',
     SELECTED_STYLE_LIST_RES:"SELECTED_STYLE_LIST_RES",
     

     //BILLING ADDRESS INFORMATION
     ADRESS_CHANGED:"ADRESS_CHANGED",
     CITY_CHANGED:"CITY_CHANGED",
     STATE_CHANGED:"STATE_CHANGED",
     ZIPCODE_CHANGED:"ZIPCODE_CHANGED",
     PHONE_NUMBER_CHANGED:"PHONE_NUMBER_CHANGED",
     BILLING_ADDRESS_RES:"BILLING_ADDRESS_RES",

     //BILLING SHIPMENT
     ADRESS_SHIPMENT_CHANGED:"ADRESS_SHIPMENT_CHANGED",
     CITY_SHIPMENT_CHANGED:"CITY_SHIPMENT_CHANGED",
     STATE_SHIPMENT_CHANGED:"STATE_SHIPMENT_CHANGED",
     ZIPCODE_SHIPMENT_CHANGED:"ZIPCODE_SHIPMENT_CHANGED",
     PHONE_NUMBER_SHIPMENT_CHANGED:"PHONE_NUMBER_SHIPMENT_CHANGED",
     BILLING_SHIPMENT_ADDRESS_RES:"BILLING_SHIPMENT_ADDRESS_RES",

     //checkScreen Status
     CHECK_SCREEN_RES:"CHECK_SCREEN_RES"


}

export default ACTION_TYPES
